name: concurrency-1
on: workflow_dispatch
concurrency:
  group: concurrency-one
  cancel-in-progress: true
jobs:
  concurrency-job:
    runs-on: ubuntu-latest
    steps: 
      - name: concurrency job-1
        run: echo "this is concurrency job"