name: env workflow
on: push
env:
  WORKFLOW_ENV_VAR: available to all jobs
jobs:
  env-job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV_VAR: available at job level
    steps:
      - name: print workflow env variable
        run: echo "$WORKFLOW_ENV_VAR"
      - name: print job env variable
        run: echo "$JOB_ENV_VAR"
      - name: print job env variable
        env:
          STEP_ENV_VAR: available at step level
        run: |
         echo "$STEP_ENV_VAR"
         echo "$JOB_ENV_VAR"
         echo "$WORKFLOW_ENV_VAR"
      
