name: variables workflow

on: push

jobs:
  var-job:
    environment: 'development'
    runs-on: ${{ vars.JOB_RUNNER }}
    env:
      ENV_NAME: ${{ vars.ENV_NAME }}
      USERNAME: ${{secrets.USERNAME}}
    steps:
      - name: display env level
        run: | 
          echo "ENV_NAMEL: $ENV_NAME"
          echo "${{vars.JOB_RUNNER}}"
          echo "username: $USERNAME"
