name: events-workflow
on: [push]
jobs:
  event-job:
    runs-on: ubuntu-latest
    steps:
      - name: display the event info of rrepo
        run: |
          echo "$GITHUB_WORKSPACE"
          echo "$GITHUB_SHA"
          echo "$GITHUB_REF"
      - name: use checkout actions
        uses: actions/checkout@v4