name: matrix workflow
on: push
jobs:
  matrix-job:
    strategy:
      matrix:
        os-version: [windows-latest, ubuntu-latest]
        node-version: [12,14,16]
        exclude:
          - node-version: [12,14]
            os-version: [windows-latest]
    runs-on: ${{ matrix.os-version }}
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}