name: matrix workflow
on: push
jobs:
  matrix-job:
    strategy:
      matrix:
        os-version: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os-version }}
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x