name: reusable workflow-1
on: workflow_dispatch
jobs:
  reusable-workflow:
      uses: rekha58044/reusable-repository/.github/workflows/reusable.yml@main
      with: 
        environment: production
            